### ISSUE TITLE
NPM Module [EPIC]

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/design-engine-playground#13]
Below are all the tasks to complete 1.0 of our NPM Module for XD submission.

- [x] Component support for nested / multiple elements (DB / Plugin / NPM) [https://github.com/de-ai/design-engine-playground/issues/26](url)

- [x] Run through 5 common screen sizes / device types. [https://github.com/de-ai/design-engine-playground/issues/33](url)

- [x] Capture and crawl all available urls from entry page [https://github.com/de-ai/design-engine-playground/issues/34](url)

- [x] Check surrounding div structure, search for hidden elements [https://github.com/de-ai/design-engine-playground/issues/35](url)

- [x] Calculate paddings / margins / box model values [https://github.com/de-ai/design-engine-playground/issues/29](url)

- [x] Parsing flexbox elements [https://github.com/de-ai/design-engine-playground/issues/30](url)
